### PR TITLE
Added game timer

### PR DESCRIPTION
**Pull request by Arc676**
Simple label shows the duration of the game
Timer stops when game is completed; check with boardModel.isCompleted()

----

Dear Lisergishnu
I enjoy playing Tetravex on Debian and, since it's open source, intended to create a Mac port. I noticed you had already started a similar project, so I created a fork of your repository to see how far along the project was and whether I could contribute.

I don't have a lot of experience, but I'm eager to learn and, as a Tetravex fan and hobbyist programmer, I would like to contribute to this project. If you would like to check my Swift coding level/style, you can take a look at my Tanks repository at (https://github.com/Arc676/Tanks). I do not have any other Swift repositories at the moment, nor do I have any serious Swift projects due to be uploaded to GitHub in the near future.

I know that this is a very small commit, but I wanted to know what you thought. I intend to add persistent times after this.

Thanks for your time and for making this project available under GPL
-Arc676/Alessandro Vinciguerra

### CODE REVIEW

**Comment by Lisergishnu** [comment]
Hey Alessandro!

Of course I'd like to have more help on this small project. I'm also no guru on this but I'm using this project as a way for developing raw Cocoa and Swift skills. I'd be more than glad to check your fork as soon as possible and I'll let you know any thoughts on it so I can merge it.

Have a nice one!
Marco

**Comment by Arc676** [comment]
Hey Marco
I just wanted to let you know that I'm done adding persistent high scores to the game.

The game timer shows the current game time in a label in `TVGameViewController` and the best times (in seconds) are stored in a dictionary that organizes them by board size and date `[String: [NSDate:Int]]`.

When presented to the user in `HighScoreViewController` in an `NSTableView`, only the times for the selected board size are shown. The dates are shown in the local time zone and are sorted from fastest to slowest.

The user has the option of deleting their high scores. The save format is incompatible between this new version and my previous method, see my commit messages for details.

-Arc676/Alessandro Vinciguerra

**Comment by Lisergishnu** [comment]
Hey Alessandro!

Thank you very much! I have your pull request very present but haven't had the time to revise it because of work! I'll do it ASAP and get back to you!

Yours,
Marco

**Comment by Lisergishnu** [comment]
It's really nice! Thank you for the effort!

**Comment by Lisergishnu** [comment]
After this I bumped the version to 0.1.2.

**Comment by Arc676** [comment]
No problem. I had a good time writing this. Thank you for the library.

**Pull request merged**
